### PR TITLE
Skip xnd tests if xnd is not installed

### PR DESCRIPTION
**Pull request by peterbell10**
I can't install XND because of xnd-project/xnd#46 so this is needed to run the test suite.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
Can you do something similar for CuPy?

**Comment by hameerabbasi** [comment]
I added Mypy back when I had a strongly-typed OOP version of `uarray`. I still feel it's good as a linter, but type-checking is basically pointless here. I'd prefer to keep it, but if you feel otherwise, feel free to remove it.

**Comment by peterbell10** [comment]
I haven't really used python typing so don't have any strong opinions on it. If you think it's worthwhile keeping then go for it.

**Comment by hameerabbasi** [comment]
Thanks, @peterbell10!

**Pull request merged**
