### PR TITLE
Add math constants Pi and Euler's number

### LINKED ISSUE #42: Add math constants Pi and Euler's number
These constants are missing in the project.

### PR DESCRIPTION
**Pull request by joaosferreira**
This resolves #42.

It seems a very simple PR. If there is a more appropriate way of adding constants please let me know.

### CODE REVIEW

**Comment by peterbell10** [comment]
It look like the format checker is failing. You need two spaces before a function definition:

https://dev.azure.com/Quansight-Labs/uarray/_build/results?buildId=543&view=logs&j=9e11e48c-707a-5a5f-a99d-b29c2c089eef&t=938ddeaa-d503-56d9-5ab9-411ba7d45da8&l=55

**Comment by hameerabbasi** [comment]
Just for context, we run automatic tests and format checks (lints) on every PR. Your code is failing the format check. If you install `black` and then run `black .` in the unumpy directory, it should fix the formatting for you.

**Comment by joaosferreira** [comment]
I looked into the `numpy` project code to see if there was a better way of defining mathematical constants and found this [file](https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/npy_math.h).

Should we take some ideas from here?

**Comment by hameerabbasi** [comment]
> Should we take some ideas from here?

Sure, but it would be a Python file; not C.

**Comment by hameerabbasi** [comment]
This has been sitting for a while; so merging.

**Pull request merged**
